# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('STOCK', '0002_auto_20170128_0510'),
        ('BASE', '0012_user_admin_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production_Finished_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BASE.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Production_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('is_started', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('from_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_stock', to='STOCK.Warehouse')),
                ('to_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_stock', to='STOCK.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Production_Raw_Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BASE.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MANUFACTURE.Production_Order')),
            ],
        ),
        migrations.AddField(
            model_name='production_finished_product',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MANUFACTURE.Production_Order'),
        ),
    ]
