# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 05:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STOCK', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse_transfer_transaction',
            name='recieved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recieved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
