# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 07:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STOCK', '0002_auto_20170128_0510'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BRANCHES', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BRANCHES.Branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STOCK.Warehouse')),
            ],
        ),
        migrations.AlterField(
            model_name='branch_stock',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BRANCHES.Branch'),
        ),
    ]
