# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 04:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BASE', '0002_treasury'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_price', models.FloatField()),
                ('is_closed', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DELIVERY.Delivery_Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Invoice_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DELIVERY.Delivery_Invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BASE.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DELIVERY.Delivery_Customer')),
                ('paid_to', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
