# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DELIVERY', '0002_auto_20170204_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_invoice',
            name='shipped_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DELIVERY.Shipping'),
        ),
    ]
