# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DELIVERY', '0003_auto_20170204_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery_customer',
            old_name='commet',
            new_name='comment',
        ),
    ]
