# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 07:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DELIVERY', '0005_auto_20170204_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_invoice',
            name='shipped_with',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BASE.User_Admin'),
        ),
        migrations.AlterField(
            model_name='delivery_invoice',
            name='shipping_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 4, 7, 33, 51, 894182)),
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
