# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DELIVERY', '0010_auto_20170204_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_invoice',
            name='shipping_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
