# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BASE', '0002_remove_system_setting_pos_from_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('total_price', models.FloatField(blank=True, default=0, null=True)),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Invoice_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PURCHASES.Purchase_Invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BASE.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('mobile', models.CharField(blank=True, max_length=16, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('mail', models.CharField(blank=True, max_length=128, null=True)),
                ('credit', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('comment', models.CharField(max_length=512)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PURCHASES.Supplier')),
            ],
        ),
        migrations.AddField(
            model_name='purchase_invoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PURCHASES.Supplier'),
        ),
    ]
