# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pos_transactions',
            name='date',
        ),
    ]
