# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0002_remove_pos_transactions_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos_transactions',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
