# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0003_pos_transactions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos_customer',
            name='credit',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
