# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0004_auto_20170127_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos_transactions',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS.POS_Customer'),
        ),
    ]
