# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('comment', models.CharField(max_length=128)),
            ],
        ),
    ]
