# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0003_expense_category_expense_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_admin',
            name='is_accounts_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_admin',
            name='is_delivery_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_admin',
            name='is_delivery_taker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_admin',
            name='is_invoice_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_admin',
            name='is_pos_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_admin',
            name='is_pos_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_admin',
            name='is_product_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_admin',
            name='is_purchases_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_admin',
            name='is_stock_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_admin',
            name='is_user_admin',
            field=models.BooleanField(default=False),
        ),
    ]
