# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0004_auto_20170129_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_admin',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
