# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0005_user_admin_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='add_to_website',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_managed',
            field=models.BooleanField(default=False),
        ),
    ]
