# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0008_auto_20170201_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pic',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
