# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0009_item_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='critical_stock',
            field=models.FloatField(default=0),
        ),
    ]
