# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0010_item_critical_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_admin',
            name='is_delivery_pilot',
            field=models.BooleanField(default=False),
        ),
    ]
