# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0011_user_admin_is_delivery_pilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_admin',
            name='mobile',
            field=models.CharField(default='', max_length=16),
        ),
    ]
