# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0012_user_admin_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='produced_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='raw_material',
            field=models.BooleanField(default=False),
        ),
    ]
