# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BASE', '0013_auto_20170204_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='BASE.Brand'),
        ),
    ]
